// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXvlXu5k6XdwNlhu13_PZ-aVVNGemfBs',
    appId: '1:584824264003:web:1d1f08feb885f1ab224bf6',
    messagingSenderId: '584824264003',
    projectId: 'loyalty-card-storage-app',
    authDomain: 'loyalty-card-storage-app.firebaseapp.com',
    storageBucket: 'loyalty-card-storage-app.firebasestorage.app',
    measurementId: 'G-T12GW98VK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5dNn-K0SNIfVtRgQQX3FS5BB2vI2aNk',
    appId: '1:584824264003:android:647a7b3bfe2a3780224bf6',
    messagingSenderId: '584824264003',
    projectId: 'loyalty-card-storage-app',
    storageBucket: 'loyalty-card-storage-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSH_b5VpRvs8BxJ6Do_f-iugXSyTiKtJQ',
    appId: '1:584824264003:ios:909b497ff4595adb224bf6',
    messagingSenderId: '584824264003',
    projectId: 'loyalty-card-storage-app',
    storageBucket: 'loyalty-card-storage-app.firebasestorage.app',
    iosBundleId: 'com.example.loyaltyCardStorageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSH_b5VpRvs8BxJ6Do_f-iugXSyTiKtJQ',
    appId: '1:584824264003:ios:909b497ff4595adb224bf6',
    messagingSenderId: '584824264003',
    projectId: 'loyalty-card-storage-app',
    storageBucket: 'loyalty-card-storage-app.firebasestorage.app',
    iosBundleId: 'com.example.loyaltyCardStorageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgXvlXu5k6XdwNlhu13_PZ-aVVNGemfBs',
    appId: '1:584824264003:web:0d94547816ab56bf224bf6',
    messagingSenderId: '584824264003',
    projectId: 'loyalty-card-storage-app',
    authDomain: 'loyalty-card-storage-app.firebaseapp.com',
    storageBucket: 'loyalty-card-storage-app.firebasestorage.app',
    measurementId: 'G-PRRL3TBT5S',
  );
}
